### ISSUE TITLE
Error starting minishift

### ISSUE THREAD

**Issue by lsnow11** [matthewmodestino/container_workshop#1]
I don't think it's actually hurting anything, but I did get an error starting minishift following the README instructions on my laptop:

> Login to server ...
> Creating initial project "myproject" ...
> Server Information ...
> OpenShift server started.
> 
> The server is accessible via web console at:
>     https://192.168.99.100:8443/console
> 
> You are logged in as:
>     User:     developer
>     Password: <any value>
> 
> To login as administrator:
>     oc login -u system:admin
> 
> 
> error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
> Error during post cluster up configuration: Unable to login to cluster

**Comment by matthewmodestino** [comment]
hey @lsnow11!! weird error. ping me on slack if you still having issues getting minishift running

**Comment by lsnow11** [comment]
I think it started OK despite the error since I got a Splunk instance running, though that has its own issues (issue #2)...

**Comment by matthewmodestino** [comment]
closing, let me know if you need any further help!
