### ISSUE TITLE
HEC not found

### ISSUE THREAD

**Issue by lsnow11** [matthewmodestino/container_workshop#2]
Everything seems to have gone fine with docker image, but I keep getting 404s for HEC

`$ curl -k https://localhost:9088/services/collector -H 'Authorization: Splunk 00000000-0000-0000-0000-000000000000'
{"text":"The requested URL was not found on this server.","code":404}`

**Comment by matthewmodestino** [comment]
hmm, are you actually using the same ports? 9088 is open on localhost? and your hec instance has the token provisioned?

**Comment by lsnow11** [comment]
As far as I can tell, yes, I'm making the connection just getting a 404 in response.  I can see the token in the GUI and everything appears to be enabled.

**Comment by matthewmodestino** [comment]
oh! are you using minishift? if so, instead of localhost, we have to send to the minishift vm ip, if you run `oc get nodes -o wide` it should present the ip the minishift vm uses to talk to the host.

**Comment by lsnow11** [comment]
Will try that once I've booted up the work laptop and let you know if that fixes it... thanks!

**Comment by lsnow11** [comment]
welp, worked with localhost this time.  thanks for looking at it!
